[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]

remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "zodiac/=lib/zodiac/contracts/",
    "safe-contracts/=lib/safe-contracts/contracts/",
    "@gnosis.pm/=node_modules/@gnosis.pm/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "safe-tools/=lib/safe-tools/src/",
    "solady/=lib/safe-tools/lib/solady/src/"
]

fs_permissions = [{ access = "read", path = "./" }]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
