[package]
authors = ["@colinnielsen"]
compiler_version = "0.22.0"
name = "dark_safe"
type = "bin"
notes = "AMDG"

[dependencies]
ecrecover = { tag = "v0.19.0", git = "https://github.com/colinnielsen/ecrecover-noir" }

